#!/usr/bin/expect

set host [lindex $argv 0]
set user [lindex $argv 1]
set pw [lindex $argv 2]

spawn bash -c "forticlientsslvpn_cli --server $host --vpnuser $user --keepalive"

expect "Password for VPN:"

send "$pw\r"

expect "Would you like to connect to this server? (Y/N)\r\n"

send "Y\r"

expect "Press Ctrl-C to quit"

interact
